voogasalad_BitsPlease: engine.render.Renderer Class Reference
engine.render.Renderer Class Reference
Public Member Functions
Renderer (Group canvas, String relativePath)
void renderGameObjects (Level level)
void createAndAssignRenderedNode (GameObject obj)
void removeRenderedNode (Identifier nodeID)
void setBackGroundImage (Level level)
Private Attributes
Group myCanvas
Map< Identifier, RenderedNode > myRenderedNodes
Level myCurrentLevel
RenderedNodeFactory myFactory
Detailed Description
Renders GameObjects on a given Canvas by generating JavaFX nodes and Images from state information
Author
Will Chang
Davis
Definition at line 20 of file Renderer.java.
Constructor & Destructor Documentation
engine.render.Renderer.Renderer (Group canvas, String relativePath)
Constructor takes in a group as the Canvas of the game
Parameters
canvas
relativePath
Definition at line 30 of file Renderer.java.
Member Function Documentation
void engine.render.Renderer.createAndAssignRenderedNode (GameObject obj)
Generates the JavaFX Node for a GameObject, giving it its image and CollisionBody
Parameters
obj
Definition at line 58 of file Renderer.java.
References engine.render.RenderedNodeFactory.createRenderedNode(), engine.gameObject.GameObject.getIdentifier(), and engine.gameObject.GameObject.setRenderedNode().
Referenced by engine.actions.render.PaintCanvas.applyRender(), engine.actions.MakeNewObjectFromLocationAction.execute(), engine.actions.render.ChangeImageTypeAction.execute(), engine.actions.MakeNewObjectFromObjectAction.execute(), engine.actions.ChangeImageIDAction.execute(), engine.actions.LabelIntIncrementAction.execute(), engine.actions.MakeNewRandomObjectAction.makeRandomObject(), and engine.render.Renderer.renderGameObjects().
void engine.render.Renderer.removeRenderedNode (Identifier nodeID)
Removes a rendered Node from the list of currently rendered Nodes
Parameters
nodeID
Definition at line 69 of file Renderer.java.
Referenced by engine.actions.render.EraseCanvas.applyRender(), engine.actions.DeleteInteractingObjectsAction.execute(), engine.actions.render.ChangeImageTypeAction.execute(), engine.actions.ChangeImageIDAction.execute(), engine.actions.DeleteTypeAction.execute(), and engine.actions.LabelIntIncrementAction.execute().
void engine.render.Renderer.renderGameObjects (Level level)
Renders all GameObjects within a Level
Parameters
level
Definition at line 40 of file Renderer.java.
References engine.render.Renderer.createAndAssignRenderedNode(), engine.level.Level.getGameObjectIterator(), engine.gameObject.GameObject.getIdentifier(), engine.gameObject.Identifier.getUniqueId(), and engine.render.Renderer.setBackGroundImage().
Referenced by engine.level.LevelManager.initializeCurrentLevel().
void engine.render.Renderer.setBackGroundImage (Level level)
Sets the background of a level
Parameters
level
Definition at line 78 of file Renderer.java.
References engine.render.RenderedNodeFactory.createImageAndView(), and engine.level.Level.getBackgroundImage().
Referenced by engine.render.Renderer.renderGameObjects().
Member Data Documentation
Group engine.render.Renderer.myCanvas private
Definition at line 21 of file Renderer.java.
Level engine.render.Renderer.myCurrentLevel private
Definition at line 23 of file Renderer.java.
RenderedNodeFactory engine.render.Renderer.myFactory private
Definition at line 24 of file Renderer.java.
Map<Identifier, RenderedNode> engine.render.Renderer.myRenderedNodes private
Definition at line 22 of file Renderer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/render/Renderer.java