voogasalad_BitsPlease: engine.render.RenderedNodeFactory Class Reference
engine.render.RenderedNodeFactory Class Reference
Public Member Functions
RenderedNodeFactory (String relativePath)
RenderedNode createRenderedNode (GameObject obj)
ImageView createImageAndView (GameObject obj)
ImageView createImageAndView (String path)
Node createCollisionBody (GameObject obj)
Label createLabel (GameObject obj)
Private Attributes
FilePathUtility myFilePathUtility
Static Private Attributes
static final String IMAGES = "images"
Detailed Description
Factory that creates RenderedNodes and their components
Author
Will Chang
Definition at line 22 of file RenderedNodeFactory.java.
Constructor & Destructor Documentation
engine.render.RenderedNodeFactory.RenderedNodeFactory (String relativePath)
Definition at line 26 of file RenderedNodeFactory.java.
Member Function Documentation
Node engine.render.RenderedNodeFactory.createCollisionBody (GameObject obj)
Creates the CollisionBody of the GameObject
Parameters
sprite
Returns
Definition at line 84 of file RenderedNodeFactory.java.
References engine.gameObject.components.PhysicsBody.getCollisionBodyHeight(), engine.gameObject.components.PhysicsBody.getCollisionBodyWidth(), and engine.gameObject.GameObject.getPhysicsBody().
Referenced by engine.render.RenderedNodeFactory.createRenderedNode().
ImageView engine.render.RenderedNodeFactory.createImageAndView (GameObject obj)
Creates the Image and ImageView for the RenderedNode if specified
Parameters
obj
Returns
Definition at line 48 of file RenderedNodeFactory.java.
References engine.gameObject.GameObject.getCurrentImageName(), engine.gameObject.GameObject.getHeight(), and engine.gameObject.GameObject.getWidth().
Referenced by engine.render.RenderedNodeFactory.createRenderedNode(), and engine.render.Renderer.setBackGroundImage().
ImageView engine.render.RenderedNodeFactory.createImageAndView (String path)
Creates the Image and ImageView for any Image specified
Parameters
obj
Returns
Definition at line 61 of file RenderedNodeFactory.java.
References engine.FilePathUtility.getFilePath().
Label engine.render.RenderedNodeFactory.createLabel (GameObject obj)
Creates the Label for a given RenderedNode
Parameters
obj
Returns
Definition at line 99 of file RenderedNodeFactory.java.
References engine.gameObject.GameObject.getHeight(), engine.gameObject.GameObject.getLabel(), and engine.gameObject.GameObject.getWidth().
Referenced by engine.render.RenderedNodeFactory.createRenderedNode().
RenderedNode engine.render.RenderedNodeFactory.createRenderedNode (GameObject obj)
Definition at line 30 of file RenderedNodeFactory.java.
References engine.render.RenderedNodeFactory.createCollisionBody(), engine.render.RenderedNodeFactory.createImageAndView(), engine.render.RenderedNodeFactory.createLabel(), engine.gameObject.GameObject.getID(), engine.gameObject.GameObject.getX(), engine.gameObject.GameObject.getY(), engine.render.RenderedNode.setCollisionBody(), engine.render.RenderedNode.setImageView(), and engine.render.RenderedNode.setLabel().
Referenced by engine.render.Renderer.createAndAssignRenderedNode().
Member Data Documentation
final String engine.render.RenderedNodeFactory.IMAGES = "images" static private
Definition at line 24 of file RenderedNodeFactory.java.
FilePathUtility engine.render.RenderedNodeFactory.myFilePathUtility private
Definition at line 23 of file RenderedNodeFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_BitsPlease/repository/src/engine/render/RenderedNodeFactory.java